### ISSUE TITLE
Dead link (software repair survey)

### ISSUE THREAD

**Issue by bloa** [geneticimprovementofsoftware/geneticimprovementofsoftware.github.io#2]
https://github.com/geneticimprovementofsoftware/geneticimprovementofsoftware.github.io/blob/075351475350483e9ef706974f5bcfc4fee8d047/faq.html#L35

The link for the software repair survey is invalid. Removing one of the two "martin/" redirects to HAL version ([https://hal.archives-ouvertes.fr/hal-01206501/file/survey-automatic-repair.pdf]()) of the technical report.
Note that the survey itself has been published since ([https://dl.acm.org/doi/10.1145/3105906]()), while a newer comprehensive survey also exists ([https://ieeexplore.ieee.org/document/8089448]()).

Hope this can help.

**Comment by geneticimprovementofsoftware** [comment]
Solved, closing.
